#!/usr/bin/env bash
# Script that configures Nginx server with a custom header

sudo apt update -y
sudo apt upgrade -y
sudo apt install nginx -y
sed -i '/listen 80 default_server/i add_header X-Served-By $HOSTNAME;' /etc/nginx/sites-available/default
sudo service nginx restart
